title: Tom A Kadavil 
logo: "/images/logo_mini.jpg?raw=true" 
description:  # your text below (remove <br> elements if you don't need line breaks)
  <br>
  NIT Calicut EEE 
  <br>
  <img src="images/NITC.png?raw=true"  width="50"/>
  <br>
  
  
  
  <br>
  PGDPA 
  <br>
  <img src="images/Amity_University_logo.png?raw=true"  width="50"/>
  <br>
  
  
  
  
  
  
  
  <a href="https://www.linkedin.com/in/tom-a-kadavil-b87284207">View My LinkedIn Profile</a> 

  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
